Development - preauthorization tiers
abrahamzaragoza/ror-final-project pull request #9
Opened 2022-10-04 03:53 UTC by abrahamzaragoza

- Add test frameworks at generators
- Add ActionText to Task
- Add ImageMagick Vips
- Add image_processing gem
- Add Board, TaskList & Task CRUD
- Update Board layout using font-awsome gem
- Add nested routes
- Add owner to boards, author to task
- Add username fields to user & authorization tier
- Update devise registration & invitation controllers
- Add Faker gem
- Add user seeds

2022-10-04 15:54 UTC, oskar-raweng requested changes
Good job creating the tests as well, Abraham. 

Just a few changes for you.

2022-10-04 15:54 UTC, oskar-raweng commented on app/controllers/application_controller.rb
> +  end
are we sure this goes here?

2022-10-04 15:54 UTC, oskar-raweng commented on app/controllers/boards_controller.rb
> +      render 'new'
a flash message with "an error has occurred" or similar, could be useful.

2022-10-04 15:54 UTC, oskar-raweng commented on app/controllers/invitations_controller.rb
> +  def create
don't you think this controller method is doing too much? 

fancy method.

2022-10-04 15:54 UTC, oskar-raweng commented on app/controllers/invitations_controller.rb
> +  def update
this one is also doing a lot.

2022-10-04 15:54 UTC, oskar-raweng commented on app/views/boards/show.html.erb
> +  <% btn_presenter = ButtonPresenter.new %>
move to first line.

2022-10-04 17:23 UTC, abrahamzaragoza commented on app/controllers/application_controller.rb
> +  end
Yes, [Devise Strong Params](https://github.com/heartcombo/devise#strong-parameters)

2022-10-04 17:36 UTC, abrahamzaragoza commented on app/controllers/boards_controller.rb
> +      render 'new'
Done, updated all the other controllers which lacked the same message.

2022-10-04 17:37 UTC, abrahamzaragoza commented on app/controllers/invitations_controller.rb
> +  def update
Method is now inherited, since I no longer need the additions that were added previously to it.

2022-10-04 17:37 UTC, abrahamzaragoza commented on app/views/boards/show.html.erb
> +  <% btn_presenter = ButtonPresenter.new %>
Done

2022-10-05 19:12 UTC, oskar-raweng approved these changes

2022-10-05 21:01 UTC, merged